### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by cbhurley** [markajoc/condvis#3]
This gives back "a" twice. It works ok for some n values!

library(condvis)

n <- 100
a <- factor(sample(4,n,replace=T))
b <- factor(sample(3,n,replace=T))
e <- factor(sample(2,n,replace=T))

d <- data.frame(a,b,e)

arrangeC(d[,c("a","b","e")])

**Comment by markajoc** [comment]
The problem is that savingby2d returns the same value for every pairing, the resulting 'saving' matrix in arrangeC is then all 1s, and the first minimum value is the first entry of the matrix, pairing 'a' and 'a'. While I'm not 100% sure if savingby2d should be returning anything different, arrangeC should certainly not return any of the diagonals from 'saving' (or pairs of the same variable), so I will fix that first.

**Comment by markajoc** [comment]
https://github.com/markajoc/condvis/commit/8f20e282a69ce4cebfca7398534e0766405cffdf
